### ISSUE TITLE
Error creating invoice: database is locked

### ISSUE THREAD

**Issue by xxdavexx23** [arindam-sahoo/invoice-app-tutorial-resource#7]
After attempting to create_invoice two subsequent times you'll get the Error creating invoice: database is locked. It does not matter whether the attempt is successful or not, this error will pop up on the second attempt

**Comment by arindam-sahoo** [comment]
Can you attach a screenshot of the Error or Popup for me to understand it better, because I didn't face the error till now like this working with SQLite, neither do my students have faced it. I appreciate your contribution

**Comment by xxdavexx23** [comment]
Sorry I figured out the error. My test script didn't close the connection to database so when trying to create a new invoice, it would not be able to. I'll close this issue, but I think if your students do the same, just a reminder to close the database every time.
